name: Keep Hugging Face Space Alive

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes
  workflow_dispatch:

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Send Keep-Alive Request
        run: |
          curl -X GET "https://amrpyt-flowise.hf.space"
